# Chess piece to MIDI instrument mapping (General MIDI program numbers)
instruments:
  P:
    program: 56  # Trumpet - bright and clear for pawns
  N:
    program: 0
  B:
    program: 0
  R:
    program: 0
  Q:
    program: 40
  K:
    program: 0

# Pitch mapping configuration
# pitch_mode options:
#   legacy                -> use original pitch_mapping grid (file to fixed note, rank *3)
#   diatonic_2rank_octaves -> files follow diatonic degrees, every 2 ranks ascend an octave
#   chromatic_linear       -> uniform chromatic spacing (file *2, rank *3)
#   major_files_octave_ranks -> files = major scale degrees, each rank = +12 semitones (strong consonance)
pitch_mode: diatonic_2rank_octaves
pitch_root: 60  # MIDI note for file 'a' base (C4)

# Velocity (volume) settings for each piece type - boosted for better overall volume
velocity:
  P: 50   # Pawns - much louder from 30
  N: 65   # Knights - boosted from 40
  B: 65   # Bishops - boosted from 40
  R: 85  # Rooks - boosted from 70
  Q: 100  # Queen - boosted from 90
  K: 127  # King - maximum velocity from 100

# Board file mapping to MIDI notes
pitch_mapping:
  a: 60  # C4
  b: 62  # D4
  c: 64  # E4
  d: 65  # F4
  e: 67  # G4
  f: 69  # A4
  g: 71  # B4
  h: 72  # C5

# Musical scale (semitone offsets from root note) - used for arpeggios and harmony
scale: [0, 2, 4, 5, 7, 9, 11]  # C Major - natural and pleasant

# Tempo progression throughout the game
tempo:
  opening: 140     # ply 1 - fast opening
  middlegame: 120  # ply 11 - moderate pace
  endgame: 90      # ply 31 - slower, contemplative

# Arpeggio behavior
arpeggios:
  threshold_seconds: 45     # Minimum EMT to trigger pre-move arpeggio (classical long think)
  enable: true              # Master switch
  max_compressed_seconds: 4 # Musical cap after compression

# Drone notes based on ECO opening classification
drones:
  enabled: true
  instrument: 95      # Organ - perfect for sustained drones
  eco_mapping:
    A: 36            # C2 - Flank openings (English, irregular) - Tonic, stable
    B: 43            # G2 - Semi-open games (1.e4 c5, c6, etc.) - Perfect 5th, stable
    C: 40            # E2 - Open games (1.e4 e5) and French - Major 3rd, warm
    D: 41            # F2 - Closed games, Queen's Gambit - Perfect 4th, tension
    E: 38            # D2 - Indian defenses - Whole step, modern/floating
  phases:
    opening:
      velocity: 110   # Boosted from 90
      duration: 16000
      harmonies: []   # Single drone note
    middlegame:
      velocity: 70    # Much louder from 30
      duration: 16000
      harmonies: [7]  # Add perfect 5th above base note
    endgame:
      velocity: 85    # Much louder from 45
      duration: 16000
      harmonies: [12] # Add octave above for resolution

# Note durations and timing
durations:
  pawn_default: 240
  piece_default: 480
  timestamp_multiplier: 400  # Much longer - notes overlap naturally
  min_duration: 200         # Longer minimum for flow
  max_duration: 3840        # Allow longer contemplative notes

effects:
  nag:
    1:  # Great move
      octave_shift: 12
      velocity_boost: 20
      duration_ratio: 0.5
      delay: 30
    2:  # Mistake
      instrument: 120
      pitch_shift: -5
      velocity_change: -30
      delay: 120
    3:  # Brilliant move - APPLAUSE!
      octave_shift: 0         # Keep natural pitch for applause
      velocity_boost: 50      # Maximum volume
      duration_ratio: 1.5     # Extended applause
      delay: 0                # Immediate recognition
      instrument: 126         # Applause - crowd goes wild!
    4:  # Blunder
      instrument: 120
      pitch_shift: -12
      velocity: 127
      duration_multiplier: 2
      delay: 60
    5:  # Speculative/interesting move
      octave_shift: 6
      velocity_boost: 10
      duration_ratio: 0.75
      delay: 45
    6:  # Inaccuracy
      pitch_shift: -2
      velocity_change: -10
      delay: 60
    7:  # Forced move
      octave_shift: 0
      velocity_boost: 15
      duration_ratio: 0.4
      delay: 0

  capture:
    pitch_shift: 7
    velocity_change: -20
    delay: 90

  check:
    pitch_shift: 6
    velocity: 70

  checkmate:
    chord: [60, 64, 67]
    velocity: 100
    duration: 960

panning:
  white: 46
  black: 81
