# Chess piece to MIDI instrument mapping (General MIDI program numbers)
instruments:
  P:
    program: 46  # Trumpet - bright and clear for pawns
  N:
    program: 46
  B:
    program: 46
  R:
    program: 46
  Q:
    program: 46
  K:
    program: 46

# Pitch mapping configuration
# pitch_mode options:
#   legacy                -> use original pitch_mapping grid (file to fixed note, rank *3)
#   diatonic_2rank_octaves -> files follow diatonic degrees, every 2 ranks ascend an octave
#   chromatic_linear       -> uniform chromatic spacing (file *2, rank *3)
#   major_files_octave_ranks -> files = major scale degrees, each rank = +12 semitones (strong consonance)
pitch_mode: diatonic_2rank_octaves
pitch_root: 60  # MIDI note for file 'a' base (C4)

# Velocity (volume) settings for each piece type - boosted for better overall volume
velocity:
  P: 50   # Pawns - much louder from 30
  N: 65   # Knights - boosted from 40
  B: 65   # Bishops - boosted from 40
  R: 85   # Rooks - boosted from 70
  Q: 100  # Queen - boosted from 90
  K: 127  # King - maximum velocity from 100

# Board file mapping to MIDI notes
pitch_mapping:
  a: 60  # C4
  b: 62  # D4
  c: 64  # E4
  d: 65  # F4
  e: 67  # G4
  f: 69  # A4
  g: 71  # B4
  h: 72  # C5

# Musical scale (semitone offsets from root note) - used for arpeggios and harmony
scale: [0, 2, 4, 5, 7, 9, 11]  # C Major - natural and pleasant

# Tempo progression throughout the game
tempo:
  opening: 140     # ply 1 - fast opening
  middlegame: 120  # ply 11 - moderate pace
  endgame: 90      # ply 31 - slower, contemplative

## (Arpeggio layer removed) -- legacy block intentionally deleted

#----------------------------------------------------------------------
# Dynamic drone modulation reacting to thinking time
#----------------------------------------------------------------------
# Drone notes based on ECO opening classification
# Each ECO category maps to a specific drone note, creating a harmonic foundation
# that reflects the character of the opening. The drone evolves through the game phases.
# The drone is played continuously in the background, with volume and harmonic content
# modulated based on the player's thinking time (see drone_modulation section).
# The drone instrument is a warm pad sound (48 - String Ensemble 1) for a rich texture.
# The drone notes are chosen to provide a stable harmonic base that complements the piece melodies.
# The drone changes subtly through the game phases to reflect the evolving nature of the game.
drones:
  enabled: true
  instrument: 48
  eco_mapping:
    A: 36            # C2 - Flank openings (English, irregular) - Tonic, stable
    B: 43            # G2 - Semi-open games (1.e4 c5, c6, etc.) - Perfect 5th, stable
    C: 40            # E2 - Open games (1.e4 e5) and French - Major 3rd, warm
    D: 41            # F2 - Closed games, Queen's Gambit - Perfect 4th, tension
    E: 38            # D2 - Indian defenses - Whole step, modern/floating
  phases:
    opening:
      velocity: 80   # Boosted from 90
      duration: 16000
      harmonies: [7]  # Perfect 5th above base note
    middlegame:
      velocity: 100
      duration: 16000
      harmonies: [4, 7, 12] # Major triad + octave
    endgame:
      velocity: 110
      duration: 16000
      harmonies: [12, 16, 19] # Rich upper harmonies

# Dynamic modulation of drone volume (CC7) based on thinking time
# This layer creates a living, breathing drone that responds to the player's thinking time.
# It uses a combination of gradual swells, tension notes, and pulsing effects to reflect
# the emotional intensity of the game.
# The modulation is applied over a compressed window of the actual thinking time,
# allowing for expressive dynamics even in shorter thinks.
# The windowing function compresses longer thinks into a manageable modulation period,
# while very short thinks may have minimal or no modulation.
drone_modulation:
  enable: true              # Master switch
  swell_min_seconds: 30     # Start subtle volume swell
  tension_min_seconds: 120  # Add temporary tension harmony (tritone)
  pulse_min_seconds: 300    # Begin pulsing phase for very long thinks
  swell_amount: 20          # CC7 increase over base phase velocity
  tension_interval: 6       # Semitones above base drone note (tritone)
  tension_velocity: 60      # Velocity for temporary tension note
  pulse_drop: -25           # Dip below base CC7
  pulse_rise: 10            # Rise above base CC7
  pulse_count: 4            # Number of dip-rise cycles
  pulse_rate_ticks: 240     # Ticks between pulse events (tempo dependent perceived rate)
  windowed:
    enable: true            # If false, revert to instantaneous modulation (no pre-move stretch)
    reference_seconds: 600  # Real thinking time that maps to reference_window_seconds
    reference_window_seconds: 15  # Compressed window length for reference_seconds think
    max_window_seconds: 22  # Hard cap for any single think window
    min_trigger_seconds: 1.0  # Ignore windows shorter than this real think time
    curve: log              # 'log' or 'pow'
    pow_exponent: 0.6       # Used only when curve == 'pow'
  # For very small thinks we don't want a window or modulation jitter.
  small_think:
    max_seconds: 1.0        # At or below this real EMT: suppress window + keep drone flat
    flat_velocity_offset: -5  # Relative to phase base velocity (negative to keep it subtle)

# Expression-aware enhancements to the pre-move thinking window.
# This layer classifies the upcoming move (based on NAG, SAN features, think length)
# and can (a) scale the compressed window duration and (b) force a higher modulation phase.
# Tags are applied per move and logged.
expression_modulation:
  enable: true
  # Multiply the computed compressed window seconds by these factors per tag
  window_multipliers:
    brilliant: 1.4   # amplify space before a brilliant move
    great: 1.2       # strong move
    blunder: 1.3     # dramatic pause before catastrophe
    mistake: 1.15
    inaccuracy: 1.05
    forced: 0.9      # shorten when it's an obvious forced reply
    check: 1.25      # spotlight a checking move
    checkmate: 1.5
    default: 1.0
  # For some tags, escalate the modulation phase regardless of raw think seconds
  # Allowed phases: idle, swell, tension, pulses (pulses maps to pulse_min_seconds behavior)
  forced_phases:
    brilliant: tension
    blunder: tension
    checkmate: pulses
    check: swell
  # Thresholds (seconds) to consider something a "long think" for classification heuristics
  long_think_seconds: 120
  epic_think_seconds: 600
  # If true, we only upscale phase (never downgrade). If false, forced phase overrides unconditionally.
  only_escalate: true


# Note durations and timing
durations:
  pawn_default: 240
  piece_default: 480
  timestamp_multiplier: 400  # Much longer - notes overlap naturally
  min_duration: 200         # Longer minimum for flow
  max_duration: 3840        # Allow longer contemplative notes

effects:
  nag:
    1:  # Great move
      octave_shift: 12
      velocity_boost: 20
      duration_ratio: 0.5
      delay: 30
    2:  # Mistake
      instrument: 120
      pitch_shift: -5
      velocity_change: -30
      delay: 120
    3:  # Brilliant move - APPLAUSE!
      octave_shift: 0         # Keep natural pitch for applause
      velocity_boost: 50      # Maximum volume
      duration_ratio: 1.5     # Extended applause
      delay: 0                # Immediate recognition
      instrument: 126         # Applause - crowd goes wild!
    4:  # Blunder
      instrument: 120
      pitch_shift: -12
      velocity: 127
      duration_multiplier: 2
      delay: 60
    5:  # Speculative/interesting move
      octave_shift: 6
      velocity_boost: 10
      duration_ratio: 0.75
      delay: 45
    6:  # Inaccuracy
      pitch_shift: -2
      velocity_change: -10
      delay: 60
    7:  # Forced move
      octave_shift: 0
      velocity_boost: 15
      duration_ratio: 0.4
      delay: 0

  capture:
    pitch_shift: 7
    velocity_change: -20
    delay: 90

  check:
    pitch_shift: 6
    velocity: 70

  checkmate:
    chord: [60, 64, 67]
    velocity: 100
    duration: 960

panning:
  white: 46
  black: 81

