# Chess piece to MIDI instrument mapping (General MIDI program numbers)
instruments:
  P:
    program: 0    # Piano
    octave_shift: 0
  N:
    program: 40   # Violin
    octave_shift: 7
  B:
    program: 68   # Oboe
    octave_shift: -5
  R:
    program: 60   # French Horn
    octave_shift: -24
  Q:
    program: 0    # Piano
    octave_shift: 0
  K:
    program: 19   # Organ
    octave_shift: 0

# Velocity (volume) settings for each piece type
velocity:
  P: 40
  N: 50
  B: 50
  R: 60
  Q: 70
  K: 60

# Board file mapping to MIDI notes
pitch_mapping:
  a: 60  # C4
  b: 62  # D4
  c: 64  # E4
  d: 65  # F4
  e: 67  # G4
  f: 69  # A4
  g: 71  # B4
  h: 72  # C5

# Musical scale (semitone offsets from root note)
scale: [0, 2, 4, 5, 7, 9, 11]  # C Major

# Tempo progression throughout the game
tempo:
  opening: 140     # ply 1 - fast opening
  middlegame: 120  # ply 11 - moderate pace
  endgame: 90      # ply 31 - slower, contemplative

# Drone notes based on ECO opening classification
drones:
  enabled: false
  instrument: 19      # Organ - perfect for sustained drones
  eco_mapping:
    A: 36            # C2 - Flank openings (English, irregular) - Tonic, stable
    B: 43            # G2 - Semi-open games (1.e4 c5, c6, etc.) - Perfect 5th, stable
    C: 40            # E2 - Open games (1.e4 e5) and French - Major 3rd, warm
    D: 41            # F2 - Closed games, Queen's Gambit - Perfect 4th, tension
    E: 38            # D2 - Indian defenses - Whole step, modern/floating
  phases:
    opening:
      velocity: 25
      duration: 16000
      harmonies: []   # Single drone note
    middlegame:
      velocity: 20
      duration: 16000
      harmonies: [7]  # Add perfect 5th above base note
    endgame:
      velocity: 30
      duration: 16000
      harmonies: [12] # Add octave above for resolution

# Note durations and timing
durations:
  pawn_default: 240
  piece_default: 480
  timestamp_multiplier: 120
  min_duration: 60
  max_duration: 1920

effects:
  nag:
    1:  # Great move
      octave_shift: 12
      velocity_boost: 20
      duration_ratio: 0.5
      delay: 30
    2:  # Mistake
      instrument: 120
      pitch_shift: -5
      velocity_change: -30
      delay: 120
    3:  # Brilliant move
      octave_shift: 24
      velocity_boost: 40
      duration_ratio: 0.25
      delay: 15
    4:  # Blunder
      instrument: 120
      pitch_shift: -12
      velocity: 127
      duration_multiplier: 2
      delay: 60
    5:  # Speculative/interesting move
      octave_shift: 6
      velocity_boost: 10
      duration_ratio: 0.75
      delay: 45
    6:  # Inaccuracy
      pitch_shift: -2
      velocity_change: -10
      delay: 60
    7:  # Forced move
      octave_shift: 0
      velocity_boost: 15
      duration_ratio: 0.4
      delay: 0

  capture:
    pitch_shift: 7
    velocity_change: -20
    delay: 90

  check:
    pitch_shift: 6
    velocity: 70

  checkmate:
    chord: [60, 64, 67]
    velocity: 100
    duration: 960

panning:
  white: 46
  black: 87
